<?php
/**
 * /home/criera/Projects/ceneac_yii/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 *
 * @var yii\web\View $this
 * @var app\models\Schedule $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="schedule-form">

    <?php $form = ActiveForm::begin([
		'id' => 'Schedule',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-error'
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


<!-- attribute course_id -->
			<?php echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'course_id')->dropDownList(
	\yii\helpers\ArrayHelper::map(app\models\Course::find()->all(), 'id', 'name'),
	[
		'prompt' => 'Select',
		'disabled' => (isset($relAttributes) && isset($relAttributes['course_id'])),
	]
); ?>

<!-- attribute start_date -->
			<?php echo $form->field($model, 'start_date')->textInput() ?>

<!-- attribute end_date -->
			<?php echo $form->field($model, 'end_date')->textInput() ?>

<!-- attribute duration -->
			<?php echo $form->field($model, 'duration')->textInput() ?>

<!-- attribute start_hour -->
			<?php echo $form->field($model, 'start_hour')->textInput(['maxlength' => true]) ?>

<!-- attribute end_hour -->
			<?php echo $form->field($model, 'end_hour')->textInput(['maxlength' => true]) ?>

<!-- attribute classroom -->
			<?php echo $form->field($model, 'classroom')->textInput(['maxlength' => true]) ?>

			<div class="row">
				<label class="control-label col-sm-3" for="schedule-classroom">Días</label>
			</div>
<!-- attribute monday -->
			<?= $form->field($model, 'monday')->checkbox(['value' => true])->label('Monday'); ?>

<!-- attribute tuesday -->
			<?= $form->field($model, 'tuesday')->checkbox(['value' => true])->label('Tuesday'); ?>

<!-- attribute wednesday -->
			<?= $form->field($model, 'wednesday')->checkbox(['value' => true])->label('Wednesday'); ?>

<!-- attribute thursday -->
			<?= $form->field($model, 'thursday')->checkbox(['value' => true])->label('Thursday'); ?>

<!-- attribute friday -->
			<?= $form->field($model, 'friday')->checkbox(['value' => true])->label('Friday'); ?>

<!-- attribute saturday -->
			<?= $form->field($model, 'saturday')->checkbox(['value' => true])->label('saturday'); ?>

<!-- attribute comments -->
			<?php echo $form->field($model, 'comments')->textarea(['rows' => 6]) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => 'Schedule',
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? 'Crear' : 'Guardar'),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
