<?php
/**
 * /home/criera/Projects/ceneac_yii/runtime/giiant/a0a12d1bd32eaeeb8b2cff56d511aa22
 *
 * @package default
 */


use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 *
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\PostulateSearch $searchModel
 */
$this->title = 'Postulates';
$this->params['breadcrumbs'][] = $this->title;

if (isset($actionColumnTemplates)) {
	$actionColumnTemplate = implode(' ', $actionColumnTemplates);
	$actionColumnTemplateString = $actionColumnTemplate;
} else {
	Yii::$app->view->params['pageButtons'] = Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']);
	$actionColumnTemplateString = "{view} {update} {delete}";
}
$actionColumnTemplateString = '<div class="action-buttons">'.$actionColumnTemplateString.'</div>';
?>
<div class="giiant-crud postulate-index">

    <?php
//             echo $this->render('_search', ['model' =>$searchModel]);
?>


    <?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>

    <h1>
        <?php echo 'Postulates' ?>
        <small>
            List
        </small>
    </h1>
    <div class="clearfix crud-navigation">
        <div class="pull-left">
            <?php echo Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
            <input type="button" class="btn btn-info" value="Aprobar" id="MyButton" >
						<input type="button" class="btn btn-danger" value="Borrar" id="delete-btn" >
        </div>

        <div class="pull-right">


            <?php echo
\yii\bootstrap\ButtonDropdown::widget(
	[
		'id' => 'giiant-relations',
		'encodeLabel' => false,
		'label' => '<span class="glyphicon glyphicon-paperclip"></span> ' . 'Relations',
		'dropdown' => [
			'options' => [
				'class' => 'dropdown-menu-right'
			],
			'encodeLabels' => false,
			'items' => [
				[
					'url' => ['schedule/index'],
					'label' => '<i class="glyphicon glyphicon-arrow-left"></i> ' . 'Schedule',
				],
				[
					'url' => ['user/index'],
					'label' => '<i class="glyphicon glyphicon-arrow-left"></i> ' . 'User',
				],

			]
		],
		'options' => [
			'class' => 'btn-default'
		]
	]
);
?>
        </div>
    </div>

    <hr />

    <div class="table-responsive">
        <?php echo GridView::widget([
		'dataProvider' => $dataProvider,
		'pager' => [
			'class' => yii\widgets\LinkPager::className(),
			'firstPageLabel' => 'First',
			'lastPageLabel' => 'Last',
		],
		'options' => ['id' => 'postulate-pjax'],
		'filterModel' => $searchModel,
		'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
		'headerRowOptions' => ['class'=>'x'],
		'columns' => [
			['class' => 'yii\grid\CheckboxColumn'],
			[
				'class' => 'yii\grid\ActionColumn',
				'template' => $actionColumnTemplateString,
				'buttons' => [
					'view' => function ($url, $model, $key) {
						$options = [
							'title' => Yii::t('yii', 'View'),
							'aria-label' => Yii::t('yii', 'View'),
							'data-pjax' => '0',
						];
						return Html::a('<span class="glyphicon glyphicon-file"></span>', $url, $options);
					}


				],
				'urlCreator' => function($action, $model, $key, $index) {
					// using the column name as key, not mapping to 'id' like the standard generator
					$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
					$params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
					return Url::toRoute($params);
				},
				'contentOptions' => ['nowrap'=>'nowrap']
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
			[
				'class' => yii\grid\DataColumn::className(),
				'attribute' => 'user_id',
				'value' => function ($model) {
					if ($rel = $model->getUser()->one()) {
						return Html::a($rel->name.' '.$rel->lastname, ['user/view', 'id' => $rel->id, ], ['data-pjax' => 0]);
					} else {
						return '';
					}
				},
				'format' => 'raw',
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
			[
				'class' => yii\grid\DataColumn::className(),
				'attribute' => 'schedule_id',
				'value' => function ($model) {
					$course = $model->getScheduleName();
					$schedule = $model->getSchedule()->one();

					list($fecha,$fakeHora) = explode(' ', $schedule->start_date);
			    list($year,$month,$day) = explode('-', $fecha);

					return Html::a($course->name, ['schedule/view', 'id' => $schedule->id, ], ['data-pjax' => 0]).' '.$day.'-'.$month.'-'.$year.' '.$schedule->start_hour;
				},
				'format' => 'raw',
			],

		],
	]); ?>
    </div>

</div>

<?php

    $this->registerJs('

    $(document).ready(function(){

	    $(\'#MyButton\').click(function(){
					var Spost_id = $(\'#postulate-pjax\').yiiGridView(\'getSelectedRows\');
	        $.ajax({
	            type: \'POST\',
	            url : \'/web/postulate/aprobar-postulados\',
	            data : {row_id: Spost_id},
	            success : function() {
	            	$.pjax.reload({container:\'#postulate-pjax\'});
	              alert("APROBADO");
	            }
	        });
	    });

			$(\'#delete-btn\').click(function(){
					var postulatesId = $(\'#postulate-pjax\').yiiGridView(\'getSelectedRows\');
					$.ajax({
							type: \'POST\',
							url : \'/web/postulate/multiple-delete\',
							data : {row_id: postulatesId},
							success : function(res) {
								if(res) {
									alert("No se puede eliminar");
								} else {
		              toastr["success"]("Postulados eliminados.");
									$.pjax.reload({container:\'#postulate-pjax\'});
								}
							}
					});
			});

    });', \yii\web\View::POS_READY);

?>

<?php \yii\widgets\Pjax::end() ?>
