<?php
/**
 * /home/criera/Projects/ceneac_yii/runtime/giiant/d4b4964a63cc95065fa0ae19074007ee
 *
 * @package default
 */

use yii\base\Model;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;
use dosamigos\tinymce\TinyMce;
use yii\bootstrap\ActiveForm;


/**
 *
 * @var yii\web\View $this
 * @var app\models\InterestList $model
 */
$copyParams = $model->attributes;

$this->title = 'Interesado en '.$model->getCourse()->one()->name;
$this->params['breadcrumbs'][] = ['label' => 'Interest Lists', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud interest-list-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?php echo \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h2>
        <?php echo $model->getUser()->one()->name.' | '.$model->getUser()->one()->email ?>
    </h2>

    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?php echo Html::a(
	'<span class="glyphicon glyphicon-pencil"></span> ' . 'Editar',
	[ 'update', 'id' => $model->id],
	['class' => 'btn btn-info']) ?>

            <?php echo Html::a(
	'<span class="glyphicon glyphicon-copy"></span> ' . 'Copiar',
	['create', 'id' => $model->id, 'InterestList'=>$copyParams],
	['class' => 'btn btn-success']) ?>

            <?php echo Html::a(
	'<span class="glyphicon glyphicon-plus"></span> ' . 'Nuevo',
	['create'],
	['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?php echo Html::a('<span class="glyphicon glyphicon-list"></span> '
	. 'Full list', ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr />

    <?php $this->beginBlock('app\models\InterestList'); ?>


    <?php echo DetailView::widget([
		'model' => $model,
		'attributes' => [
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'user_id',
				'value' => ($model->getUser()->one() ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['user/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getUser()->one()->name, ['user/view', 'id' => $model->getUser()->one()->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'InterestList'=>['user_id' => $model->user_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'course_id',
				'value' => ($model->getCourse()->one() ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['course/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->getCourse()->one()->name, ['course/view', 'id' => $model->getCourse()->one()->id, ]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'InterestList'=>['course_id' => $model->course_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
		],
	]); ?>


    <hr/>

    <?php echo Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Borrar', ['delete', 'id' => $model->id],
	[
		'class' => 'btn btn-danger',
		'data-confirm' => '' . 'Esta seguro que desea eliminar el interesado?' . '',
		'data-method' => 'post',
	]); ?>
    <?php $this->endBlock(); ?>

    <hr />


    <?php echo Tabs::widget(
	[
		'id' => 'relation-tabs',
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => '<b class=""># '.$model->id.'</b>',
				'content' => $this->blocks['app\models\InterestList'],
				'active'  => true,
			],
		]
	]
);
?>
<!-- mail form -->
<br>
<div class="custom-mail">
  <h3>Contactar</h3>
  <form method="post">
    <textarea id="mail-body" ></textarea>
  </form>
  <br>
  <div class="form-group">
      <?= Html::submitButton('Enviar', ['class' => 'btn btn-primary', 'id' => 'send-btn']) ?>
  </div>
          <!-- user email -->
  <div id="userEmail" style="visibility: hidden;">
    <?php echo $model->getUser()->one()->email ?>
  </div>
</div>
<!-- End mail form -->
<?php
$this->registerJs('
    $(document).ready(function(){
      tinymce.init({
        selector: "#mail-body",
         height: 240
      });
	    $(\'#send-btn\').click(function(){
        var body = tinymce.get("mail-body").getContent();
        var userEmail = $("#userEmail").text().trim();
        $(this).attr("disabled", true);
        $(this).css("pointer-events", "none");
        $.ajax({
             type: \'POST\',
             url : \'/web/interest-list/send-mail\',
              data : {body: body, email: userEmail},
             success : function(res) {
               $(\'#send-btn\').attr("disabled", false);
               $(\'#send-btn\').css("pointer-events", "auto");
               tinymce.get("mail-body").setContent("");
               toastr["success"]("Correo Enviado.");
             },
             error: function(err) {
               console.log(err);
               $(\'#send-btn\').attr("disabled", false);
               $(\'#send-btn\').css("pointer-events", "auto");
               toastr["error"]("Ha ocurrido un error");
             }
         });
	    });
    });', \yii\web\View::POS_READY);  ?>
</div>
