<?php
/**
 * /home/criera/Projects/ceneac_yii/runtime/giiant/4b7e79a8340461fe629a6ac612644d03
 *
 * @package default
 */


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;
use app\models\User;
use app\models\Schedule;

/**
 *
 * @var yii\web\View $this
 * @var app\models\Preregistered $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="preregistered-form">

    <?php $form = ActiveForm::begin([
		'id' => 'Preregistered',
		'layout' => 'horizontal',
		'enableClientValidation' => true,
		'errorSummaryCssClass' => 'error-summary alert alert-error'
	]
);
?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


<!-- attribute user_id -->
			<?php
      $array = array();
      $users = User::find()->all();
      foreach ($users as $item) {
          $keyvalue = array();
          $keyvalue['id'] = $item->id;
          $keyvalue['fullname'] = $item->name.' '.$item->lastname.' | '.$item->ci;
          $array[] = $keyvalue;
      }
  echo
$form->field($model, 'user_id')->dropDownList(
	\yii\helpers\ArrayHelper::map($array, 'id', 'fullname'),
	[
		'prompt' => 'Select',
		'disabled' => (isset($relAttributes) && isset($relAttributes['user_id'])),
	]
); ?>

<!-- attribute schedule_id -->
			<?php
      // new array with an extra field (correct format to show)
      $array = array();
      $items = Schedule::find()->all();
      foreach ($items as $item) {
          $keyvalue = array();
          $keyvalue['id'] = $item->id;
          list($fecha,$fakeHora) = explode(' ', $item->start_date);
          list($year,$month,$day) = explode('-', $fecha);
          $format = $item->getCourse()->one()->name.' '.$day.'-'.$month.'-'.$year.' '.$item->start_hour;
          $keyvalue['format'] = $format;
          $array[] = $keyvalue;
      }
      // return var_dump($array);
      echo // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'schedule_id')->dropDownList(
	\yii\helpers\ArrayHelper::map($array, 'id', 'format'),
	[
		'prompt' => 'Select',
		'disabled' => (isset($relAttributes) && isset($relAttributes['schedule_id'])),
	]
); ?>

<!-- attribute preregister_date -->
			<?php echo $form->field($model, 'preregister_date')->textInput() ?>

<!-- attribute status -->
			<?php //echo $form->field($model, 'status')->textInput() ?>
    <?php  echo $form->field($model, 'status')->dropDownList([1=>'Aprobado', 0=>'Por Pagar']) ?>

<!-- attribute comments -->
			<?php echo $form->field($model, 'comments')->textarea(['rows' => 6]) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?php echo
Tabs::widget(
	[
		'encodeLabels' => false,
		'items' => [
			[
				'label'   => 'Preregistered',
				'content' => $this->blocks['main'],
				'active'  => true,
			],
		]
	]
);
?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?php echo Html::submitButton(
	'<span class="glyphicon glyphicon-check"></span> ' .
	($model->isNewRecord ? 'Crear' : 'Save'),
	[
		'id' => 'save-' . $model->formName(),
		'class' => 'btn btn-success'
	]
);
?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
